### ISSUE TITLE
separate cron job  and webserver logic

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_protocols_web#14]
crontab을 통해 caching작업을 하는 로직과 RESTAPI를 제공하는 웹서버 구현을 분할함으로써 각 역할을 명확히하여 나눠서 사용이 가능해야합니다.

**Comment by jihoonl** [comment]
또한 cron job을 하는 script는 라이브러리화하여 database또는 다른 장소(예: github등)에 올리는 로직을 구현할 수 있도록 구조화되야합니다.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/msg_database/issues/14#issuecomment-69137590 를위한 이슈를 등록하였습니다. https://github.com/robotics-in-concert/msg_database/issues/19

**Comment by eskim** [comment]
현재는 index.js 를 실행하면 웹인터페이스(REST API)와 스케쥴러 동시에 실행이 됩니다.
이를 파일자체를 분리하는게 어떨까요?

* `scheduler.js --config /path/to/config.json` : 스케쥴링만 실행
* `web.js --config /path/to/config.json` : 웹 인터페이스 실행

**Comment by jihoonl** [comment]
네 좋을것 같습니다. scheduler의 경우 webserver에서 빠져서 web_fetch내에 들어가는게 어떨까요?

**Comment by eskim** [comment]
`rocon_protocols_web_fetch` 는 제 생각에는 순수하게 fetch 하는 로직만 들어가는게 맞는것 같습니다.
(`rocon_protocols_web_fetch`는 npm package 로 등록이 될 것이고요)

현재 rocon_protocols_webserver 에 있는 sync 관련 코드는 `rocon_protocols_web_fetch` npm package 를 이용하는 클라이언트 형태가 되는 것으로 작업했습니다.

만약 애매한 부분이 있다면 sync 관련 코드를 rocon_protocols_sync 라는 폴더를 추가하여 별도로 구성하는 것은 어떨까요?

**Comment by jihoonl** [comment]
아 그렇군요. 알겠습니다. `web_server` 로직내에 `web_fetch` 가 아직 통합이 안되있는것 같아서 그랬었습니다. 굳이 sync 패키지를 만들이유는 없을것 같습니다.

**Comment by eskim** [comment]
88559f7becfcd4aa34141447445da0860a9d9ba6 분리하였습니다.
* schedule.js
* web.js

**Comment by eskim** [comment]
304da9b75cd8c4ce94a2b4adaf76949268f63fe5 README 수정.
