### ISSUE TITLE
README for webserver and cron job script

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_protocols_web#15]
이후 사용을 위해서 RESTAPI 서버 및 cron job 스크립트에 다음 내용들이 문서화가 되면 좋겠습니다.

* 설치법
* 설정가능한 환경변수들
* 구동방법
* api 및 사용 예시

**Comment by eskim** [comment]
구글 드라이브에 작성된 기존의 msg_database 문서를 기반으로
최근 업데이트된 내용을 포함하여 프로젝트 README 파일을 수정하였습니다.

한번 확인해 보시고, 추가할 사항이나 잘못된 부분이 있으면 말씀해 주세요.

**Comment by eskim** [comment]
1차 문서화 완료.
