### ISSUE TITLE
각 설정변수들을 위한 default value들 만들기

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_protocols_web#18]
*https://github.com/robotics-in-concert/msg_database/issues/13#issuecomment-69294487 에서 나온 이야기입니다.*

현재 모든 distro의 url(rocon_apps, and hic_apps)들을 환경변수들을 통해서 설정하게 되어있습니다.

각 변수들을 현재 open repository의 url들을 기본값으로 설정해놓고 환경변수를 통해서 재설정을 가능하게 만들기

**Comment by eskim** [comment]
#23 작업중입니다.

**Comment by eskim** [comment]
작업 완료.
