### ISSUE TITLE
distro 동기화를 하는 로직의 라이브러리화

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_protocols_web#19]
또한 cron job을 하는 script는 라이브러리화하여 database또는 다른 장소(예: github등)에 올리는 로직을 구현할 수 있도록 구조화되야합니다.

**Comment by eskim** [comment]
`rocon_protocols_web_fetcher` 라는 폴더를 만들어서 npm package 를 만드는 작업을 진행중입니다.
rocon_protocols_web_fetcher 라는 이름이 어떠신지요?

라이브러리화를 하다보니 sync 하는 기능은 라이브러리의 클라이언트에서 하게될 것이고,
라이브러리에서는 fetch 하는 기능이 주가 되다보니 이렇게 이름을 정해 보았습니다.

어떻게 생각하시는지요?

**Comment by jihoonl** [comment]
제생각에는 er를 빼고 `rocon_protocols_web_fetch`로 하는게 더 부드러워보입니다. 이 모듈을 사용하기 위해서는 어떤 환경이 갖춰줘야하나요? 예를들어서 ROS환경이 있어야한다던가 ros dependency 어떤 모듈이 설치되어있어야한다는게 있을까요?

**Comment by eskim** [comment]
그럼 er은 빼도록 하겠습니다.

의존정보와 사용법은 작업 완료후 문서화하겠습니다

**Comment by eskim** [comment]
er은 전부 뺐습니다.

간단하게  README 파일 수정했습니다. [README.md](/robotics-in-concert/rocon_protocols_web/blob/libfy/rocon_protocols_web_fetch/README.md)

그럼 확인해 보시고 필요한 부분 커멘트 주시고 아니면 close 해주세요.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_protocols_web/issues/14#issuecomment-70025602 에서 이야기한 것처럼 scheduler.js 가 web_fetch로 온다면 서로간의 dependency는 없을듯 한데 npm 모듈 dependency외에 ROS관련 dependency(또는 사용 명령어)는 어떤 것이 있을까요?

**Comment by eskim** [comment]
ROS dependency 관련하여
fetch 패키지의 실행 조건은

1. `rosmsg list` 가 실행될 수 있어야 한다.
1. `rosrun msg_database_scripts convert_msg_spec_to_json.py [type]` 명령어가 실행 가능해야 한다.

정도가 되겠네요.

**Comment by jihoonl** [comment]
음 그렇다면 ros-indigo-rosmsg 시스템 dependency가 있는데 이걸 명시적으로 기입할 방법이 있을까요?
그리고 

https://github.com/robotics-in-concert/rocon_protocols_web/blob/libfy/rocon_protocols_web_fetch/lib/msg.js#L12 가 msg_database_scripts에서 rocon_protocols_web_scripts가 되어야 될듯 합니다.

**Comment by eskim** [comment]
[https://www.npmjs.com/package/rocon_protocols_web_fetch](https://www.npmjs.com/package/rocon_protocols_web_fetch) npm package 등록 되었습니다.

**Comment by eskim** [comment]
7b2c2b6e08cd427876b6e84a9ec22ea17d35b015 sync 관련 코드가 npm 패키지 이용하도록 수정 하였습니다.
이 정도에서 close 하면 될 것 같습니다.
