### ISSUE TITLE
웹서버설정을 위한 환경변수 이용방법

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_protocols_web#20]
@eskim @hughie @dwlee 

현재는 다음 설정들을 환경변수를 통해서 변경합니다.

* address
* port
* rocon_apps_url
* hic_apps_url

이후에 service profile, custom message repo urls등 지속적으로 사용성을 확장하게 되면 너무 많은 환경변수들을 이용하게 될것같아 걱정이 됩니다.

모든 설정들을 전부 환경변수로 빼는 대신에 configuration파일 한개를 환경변수로 받아서 그 내부적으로 설정들을 하는 방법이 있을꺼 같은데 어떻게들 생각하시나요?

**Comment by hughie** [comment]
지속적으로 환경 변수가 늘어날 것 같다면, 저도 configuration 파일 하나를 환경 변수로 설정하고 설정 파일에 내용을 담는것이
낫다고 생각합니다.

2015년 1월 9일 오후 4:04, Jihoon Lee <notifications@github.com>님이 작성:

**Comment by eskim** [comment]
df6d0e3 config file로 설정하는 방식으로 수정하였습니다

**Comment by jihoonl** [comment]
config 파일의 위치를 환경 변수로 받아서 사용할 수 있을까요? 그렇게 한다면 이후에 다른 설정을 사용해야한더라도 패키지 수정없이 사용할수 있어서 좋을것 같습니다.

**Comment by eskim** [comment]
실행변수로 처리하는게 더 좋을 것 같습니다. 예 mongodb redis 등

**Comment by jihoonl** [comment]
넵 실행변수처리가 더 좋겠네요.

**Comment by eskim** [comment]
그럼 순서가...

(실행변수 예, --config /path/to/config/config.json) 


1. 실행 변수가 설정되어 있지 않을 경우는 디폴트로 프로젝트 root 의 config.json 파일 참조
2. 실행 변수가 있을 경우 해당 파일 참조.

이렇게 처리하면 되겠지요?

**Comment by jihoonl** [comment]
네 그러면 될꺼 같습니다.

**Comment by eskim** [comment]
595ad9ea384c71981a070d32871d48e142f55f0d 수정 완료. close 하겠습니다.
